config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :collections, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :user_collections, only: [:create, :destroy]
  resources :user, only: [:show]
  resources :activities, only: [:create, :new, :show, :edit, :update, :destroy]
  resources :user_activities, only: [:create, :edit, :update, :destroy]
  resources :contacts, only: [:create, :destroy]
  resources :promote_activities, only: [:new, :create, :index, :destroy]
  resources :activity_collections, only: [:create, :destroy]

  get 'pages/index'
  get 'pages/configuration'
  get 'pages/politica'

  get 'user_calendar/:id', to: 'user#user_calendar', as: 'user_calendar'
  patch 'edit_calendar/:activity_id', to: 'user#update_calendar', as: 'update_user_calendar'
  
 

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        :omniauth_callbacks => "user/omniauth_callbacks",
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :activity_collection, dependent: :destroy
	has_many :activities, through: :activity_collection, dependent: :destroy
	mount_uploader :photo, ImageUploader

	has_many :user_collection, dependent: :destroy
	has_many :users, through: :user_collection, dependent: :destroy

	belongs_to :user, class_name: 'User', foreign_key: :owner_id
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController


  
  def show
  	@collection = Collection.find(params[:id])
    authorize! :show, @collection

  	if user_signed_in?
      
      @contacts = User.find(current_user.id).contacting
      @contacts_collection = []
      @collection.users.each do |user|
        @contacts.each do |contact|
          if user.id == contact.followed_id
            @contacts_collection << User.find(contact.followed_id)
          end
        end
      end

	  	if UserCollection.where(user_id: current_user.id, collection_id: params[:id]) != []
	  		@registrada = true
	  	else
	  		@registrada = false
	  	end
	  end

    

  end


  def new
  	@collection = Collection.new
    authorize! :new, @collection
  end

  def create
  	@collection = Collection.new
  	@collection.name = params[:collection][:name]
  	@collection.photo = params[:collection][:photo]
  	@collection.remote_photo_url = params[:collection][:remote_photo_url]
  	@collection.owner_id = current_user.id
    authorize! :create, @collection
  	@collection.save
  	redirect_to edit_collection_path(@collection), notice: 'collection fue creada'
  end

  def edit
  	@collection = Collection.find(params[:id])
    authorize! :edit, @collection
    @col_activities = ActivityCollection.eager_load(:activity).where(collection_id: params[:id])
    @activities = Activity.all
  end

  def update
  	@collection = Collection.find(params[:id])
    authorize! :update, @collection
  	@collection.update(name: params[:collection][:name])
  	@collection.update(photo: params[:collection][:photo])
  	@collection.update(remote_photo_url: params[:collection][:remote_photo_url])
  	redirect_to collection_path(@collection), notice: 'collection fue editada'
  end

  def destroy
    @collection = Collection.find(params[:id])
    authorize! :destroy, @collection
    @collection.destroy
    redirect_to pages_configuration_path, notice: 'la colección fue borrada'
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/edit.html.erb
<h2>Editar Colección </h2>
<br>
<% if user_signed_in? %>
	<%= form_with model: @collection, url: collection_path(@collection), method: :patch, local: true do |f| %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>	<br>

	    <%= f.label :photo %> <br>
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><br>

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>
<br><br>
<h5>Actividades en esta colección:</h5>
<table>
<% @col_activities.each do |act| %>
	<tr>
		<td class="elemento-edit-col"><%= link_to act.activity.name, activity_path(act.activity) %></td>
		<td><%= link_to 'Borrar de la lista', activity_collection_path(act), method: :delete, :class => 'btn boton-tipo-chico' %> </td>
	</tr>
<% end %>
</table>
<br>
<h6>Agregar actividad:</h6>

<%= form_with model: @collection, url: activity_collections_path(:collection_id => @collection.id), method: :post, local: true do |f| %>

	<%= f.label :seleccionar_actividad %>
	<%= f.collection_select :activity_id, @activities, :id, :name, :prompt => true %>

	<%= f.submit "Enviar" %>

<% end %>

app/views/collections/new.html.erb
<h2>Crear nueva Colección </h2>
<br>

<% if user_signed_in? %>
	<%= form_with model: @collection, url: collections_path, method: :post, local: true do |f| %>
		
		<%= f.label :nombre %>: 
		<%= f.text_field :name %>	<br>

	    <%= f.label :imagen %>: 
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><i>(puede subir una imagen o copiar el enlace de una imagen extraída de internet)</i><br><br>

		<%= f.submit "Crear Colección | Pasar a agregar actividades", :class => 'btn boton-config-titulo' %>

	<% end %>
<% end %>

app/views/collections/show.html.erb
<div id="fondo-act" class="fondo_activity">

	<div class="cuadro_centro_col">
		<div class="row">
			<div class="col-12 col-md-6">
				<h3 class="titulo-col"><%= @collection.name %></h3>
				<p class="titulo-col">Propietario de esta colección: <%= link_to @collection.user.name, user_path(@collection.user) %></p>
				<br>
				<img src="<%= @collection.photo.normal %>">
				<br><br>
				<% if can? :edit, @collection %>
					<%= link_to 'Editar esta colección', edit_collection_path(@collection), :class => 'btn btn-sm boton-tipo' %>
				<% end %>
				<br><br><br><br>
				<h5 class="titulo-col">Contactos que siguen esta Colección:</h5>
				<% if user_signed_in? %>
					<% @contacts_collection.each do |contact| %>
						<ul class="color-rojo-col">
							<li><%= link_to contact.name, user_path(contact) %></li>
						</ul>
					<% end %>
				<% end %>
			</div>

			<div class="col-12 col-md-6">
				<% if @registrada %>
					<%= link_to 'Dejar de seguir esta Colección', user_collection_path(@collection.id), method: :delete, :class => 'btn boton-tipo' %>
				<% else %>
					<%= link_to 'Seguir esta Colección', user_collections_path(:collection_id => @collection.id), method: :post, :class => 'btn boton-tipo' %>
				<% end %>
				<br><br><br><br>
				<h5 class="titulo-col">Actividades en esta colección:</h5>
				<ol class="color-rojo-col">
					<% @collection.activities.each do |activity| %>
						<li><h6><%= link_to activity.name, activity_path(activity) %>
							<% if user_signed_in? %>
								<% current_user.activities.each do |my_act| %>
									<% if my_act.id == activity.id %>
										<i class="titulo-col">actividad realizada</i>
									<% end %>
								<% end %>
							<% end %>

						</h6></li>
					<% end %>
				</ol>

			</div>
			
			<br>

		</div>
		

		<img src="<%= @collection.photo %>" id="lo" style="display: none">
	</div>
</div>

<script>
		
		$("#fondo-act").backstretch(document.getElementById("lo").src)
		
		

</script>