config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :collections, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :user_collections, only: [:create, :destroy]
  resources :user, only: [:show]
  resources :activities, only: [:create, :new, :show, :edit, :update, :destroy]
  resources :user_activities, only: [:create, :edit, :update, :destroy]
  resources :contacts, only: [:create, :destroy]
  resources :promote_activities, only: [:new, :create, :index, :destroy]
  resources :activity_collections, only: [:create, :destroy]

  get 'pages/index'
  get 'pages/configuration'
  get 'pages/politica'

  get 'user_calendar/:id', to: 'user#user_calendar', as: 'user_calendar'
  patch 'edit_calendar/:activity_id', to: 'user#update_calendar', as: 'update_user_calendar'
  
 

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        :omniauth_callbacks => "user/omniauth_callbacks",
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  enum role: [:admin, :player]
  attribute :role, :integer, default: :player

  has_many :user_activity
  has_many :activities, through: :user_activity
  has_many :promote_activity
  has_many :billings

  has_many :ownactivity, class_name: 'Activity', foreign_key: :owner_id

  has_many :owncollection, class_name: 'Collection', foreign_key: :owner_id

  has_many :contacting, class_name: 'Contact', foreign_key: :user_id
  has_many :contacted, class_name: 'Contact', foreign_key: :followed_id

  mount_uploader :photo, ImageUploader

  has_many :user_collection
  has_many :collections, through: :user_collection

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      redirect_to root_path, notice: 'Error al iniciar sesión con Facebook.'
    end
    
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:birth,:role,:country,:city,:photo,:remote_photo_url])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:birth,:country,:city,:photo,:remote_photo_url])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  authorize_resource :class => UserController

  def show
  	@user = User.find(params[:id])


    #if user_signed_in?
      @user_act_done = UserActivity.realizadas.eager_load(activity: :category).where(user_id: params[:id]).order(:created_at).reverse
      @titulo_done = "Actividades Realizadas"  if @user_act_done != []
      @user_act_wish = UserActivity.por_realizar.eager_load(activity: :category).where(user_id: params[:id]).order(:created_at).reverse
      @titulo_wish = "Actividades Por Realizar"  if @user_act_wish != []

      @cats_user_done = []
      @user_act_done.each do |act|
        if @cats_user_done.include? act.activity.category
        else
          @cats_user_done << act.activity.category
        end
      end

      @cats_user_wish = []
      @user_act_wish.each do |act|
        if @cats_user_wish.include? act.activity.category
        else
          @cats_user_wish << act.activity.category
        end
      end

      @user_collections = UserCollection.eager_load(:collection).where(user_id: params[:id]).order(:created_at).reverse
    #end

    @my_activities = UserActivity.where(user_id: @user.id, status: "realizada")

    if user_signed_in?
      if current_user.contacting.find_by(followed_id: @user.id) != nil
        @following = true
      else
        @following = false
      end
    end

    @trek = UserActivity.eager_load(activity: :category).where(user_id: params[:id])
    @trekking = []
    @trek.each do |i|
      if i.activity.category.id == 3
        @trekking << i
      end
    end

    @hash = Gmaps4rails.build_markers(@trekking) do |trek, marker|
      marker.lat trek.activity.latitude
      marker.lng trek.activity.longitude
      marker.infowindow trek.activity.name
    end
  end


  def user_calendar
    @user = User.find(params[:id])
    @act_user_por_realizar = UserActivity.where(user_id: params[:id], status: 'por_hacer')
  end

  def update_calendar
    @user_activity = UserActivity.find(params[:activity_id])
    authorize! :update_calendar, @user_activity
    @user_activity.update(start: params[:user_activity][:start])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/show.html.erb
<div class="titulo-user">
	<div class="letra-circulo">
		<%= @user.name[0].capitalize %>
	</div>
	<h4 class="nombre-user">Colecciones de<br><%= @user.name %></h4>
</div>


<div class="row">
	<div class="col-12 col-md-5 row recuadro-user-resumen">

			<div class="foto-user col-5">
				<img src="<%= @user.photo.normal %>" class="foto_usuario"> 
			</div>
			<div class="col-7 mt-5">
				<% @cats_user_done.each do |category| %>
					<ul>
					<li class="listado-user"><strong>Total de <%= category.sustantivo %> que <%= category.past %>:
						<%= @my_activities.where(category: category.name).count %></strong></li>
					</ul>
				<% end %>
				
			</div>

	</div>
	<div class="col-12 col-md-7">
		<h6 class="div-coleccion mt-1 mb-2">Colecciones</h6>
		<div class="row">
			<% @user_collections.each do |coll| %>

				<div class="col-4 recuadro-coleccion">
					<img src="<%= coll.collection.photo.normal %>" class="foto-coleccion"><br>
					<%= link_to coll.collection.name, collection_path(coll.collection), :class => "coleccion-nombre" %>
				</div>

			<% end %>
		</div>
	</div>
</div>

<br>



<% if user_signed_in? && @following %>
	<%=link_to "Dejar de seguir a #{@user.name}", contact_path(:id => @user.id), method: :delete, :class => 'btn boton-config-titulo' %>
<% elsif user_signed_in? && @user.id != current_user.id %>
	<%=link_to "Seguir a #{@user.name}", contacts_path(:id => @user.id), method: :post, :class => 'btn boton-config-titulo'  %>
<% end %>
<br><br>

<div class="row">
	<div class="col-12 col-md-5 pl-0 pr-2" >
		<%if @trekking != [] %>
			<h6 style="text-align:center;">Trekkings y lugares visitados</h6>
		 	<div id="map" style="height: 240px;"></div>
		<% end %>
	</div>


	<% if @my_activities != [] %>
		<div class="col-12 col-md-7">
			<h6 style="text-align:center">Actividades por año</h6>
			<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
			<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
			
			<%= line_chart @my_activities.group(:category).group_by_year(:start).count, height:"240px" %>
		</div>
	<% end %>

</div>
<br>
<hr>

<div class="row">
	<div class="col-12 col-md-6">
		<h5><%= @titulo_done %></h5>

		<% @cats_user_done.each do |category| %>
			<h6><%= category.sustantivo %> que <%= category.past %></h6>
			<div style="margin: 0 0 10px">
				<% @user_act_done.each do |suceso| %>
					<% if suceso.activity.category_id == category.id %>
						
						<div class="row">
							<div style="float: left; margin-left: 20px;">
								<img src="<%= suceso.activity.photo.thumb %>" >
							</div>
							<div style="float: left; margin: 0 0 5px 5px;">
								<%= link_to suceso.activity.name, activity_path(suceso.activity) %><br>
								<%= category.participio %> el <%= suceso.start.strftime("%F") %>
								<% if can?(:destroy, suceso) %>
									<%= link_to 'Editar', edit_user_activity_path(suceso) %>
									<%= link_to 'Borrar', user_activity_path(suceso), method: :delete %>
								<% end %>
							</div>
						</div>

					<% end %>
				<% end %>
			</div>
		<% end %>
		
	</div>

	<div class="col-12 col-md-6">
		<% if @titulo_wish %>
			<h5><%= @titulo_wish %><%= link_to "Ver en Calendario", user_calendar_path(@user.id), :class=> 'btn boton-config-titulo float-right', :style=> 'width:180px;' %></h5>			
		<% end %>

		<% @cats_user_wish.each do |category| %>
			<h6><%= category.sustantivo %> que <%= category.futuro %></h6>
			<div style="margin: 0 0 10px">
				<% @user_act_wish.each do |suceso| %>
					<% if suceso.activity.category_id == category.id %>
						
						<div class="row">
							<div style="float: left; margin-left: 20px;">
								<img src="<%= suceso.activity.photo.thumb %>" >
							</div>
							<div style="float: left; margin: 0 0 5px 5px;">
								<%= link_to suceso.activity.name, activity_path(suceso.activity) %><br>
								planificada para el <%= suceso.start.strftime("%F") %>
								<% if can?(:destroy, suceso) %>
									<%= link_to 'Editar', edit_user_activity_path(suceso) %>
									<%= link_to 'Borrar', user_activity_path(suceso), method: :delete %>
								<% end %>
							</div>
						</div>

					<% end %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>


<br><br>


<%if @trekking != [] %>

	<script>
		
		handler = Gmaps.build('Google');
		handler.buildMap({
			provider: {
				center: new google.maps.LatLng({ lat: <%= @trekking.last.activity.latitude %>, lng: <%= @trekking.last.activity.longitude %> }),
	      		zoom: 8,
	      		controlSize: 8,
	      		styles: [
	              {elementType: 'geometry', stylers: [{color: '#ebe3cd'}]},
	              {elementType: 'labels.text.fill', stylers: [{color: '#523735'}]},
	              {elementType: 'labels.text.stroke', stylers: [{color: '#f5f1e6'}]},
	              {
	                featureType: 'administrative',
	                elementType: 'geometry.stroke',
	                stylers: [{color: '#c9b2a6'}]
	              },
	              {
	                featureType: 'administrative.land_parcel',
	                elementType: 'geometry.stroke',
	                stylers: [{color: '#dcd2be'}]
	              },
	              {
	                featureType: 'administrative.land_parcel',
	                elementType: 'labels.text.fill',
	                stylers: [{color: '#ae9e90'}]
	              },
	              {
	                featureType: 'landscape.natural',
	                elementType: 'geometry',
	                stylers: [{color: '#dfd2ae'}]
	              },
	              {
	                featureType: 'poi',
	                elementType: 'geometry',
	                stylers: [{color: '#dfd2ae'}]
	              },
	              {
	                featureType: 'poi',
	                elementType: 'labels.text.fill',
	                stylers: [{color: '#93817c'}]
	              },
	              {
	                featureType: 'poi.park',
	                elementType: 'geometry.fill',
	                stylers: [{color: '#a5b076'}]
	              },
	              {
	                featureType: 'poi.park',
	                elementType: 'labels.text.fill',
	                stylers: [{color: '#447530'}]
	              },
	              {
	                featureType: 'road',
	                elementType: 'geometry',
	                stylers: [{color: '#f5f1e6'}]
	              },
	              {
	                featureType: 'road.arterial',
	                elementType: 'geometry',
	                stylers: [{color: '#fdfcf8'}]
	              },
	              {
	                featureType: 'road.highway',
	                elementType: 'geometry',
	                stylers: [{color: '#f8c967'}]
	              },
	              {
	                featureType: 'road.highway',
	                elementType: 'geometry.stroke',
	                stylers: [{color: '#e9bc62'}]
	              },
	              {
	                featureType: 'road.highway.controlled_access',
	                elementType: 'geometry',
	                stylers: [{color: '#e98d58'}]
	              },
	              {
	                featureType: 'road.highway.controlled_access',
	                elementType: 'geometry.stroke',
	                stylers: [{color: '#db8555'}]
	              },
	              {
	                featureType: 'road.local',
	                elementType: 'labels.text.fill',
	                stylers: [{color: '#806b63'}]
	              },
	              {
	                featureType: 'transit.line',
	                elementType: 'geometry',
	                stylers: [{color: '#dfd2ae'}]
	              },
	              {
	                featureType: 'transit.line',
	                elementType: 'labels.text.fill',
	                stylers: [{color: '#8f7d77'}]
	              },
	              {
	                featureType: 'transit.line',
	                elementType: 'labels.text.stroke',
	                stylers: [{color: '#ebe3cd'}]
	              },
	              {
	                featureType: 'transit.station',
	                elementType: 'geometry',
	                stylers: [{color: '#dfd2ae'}]
	              },
	              {
	                featureType: 'water',
	                elementType: 'geometry.fill',
	                stylers: [{color: '#b9d3c2'}]
	              },
	              {
	                featureType: 'water',
	                elementType: 'labels.text.fill',
	                stylers: [{color: '#92998d'}]
	              }
	            ],

			},
			internal: {
				id: 'map'
				}
			},
		function(){
		  markers = handler.addMarkers(<%= raw @hash.to_json %>);		  
		});

	</script>
	
<% end %>

app/views/user/user_calendar.html.erb
<div class="titulo-user">
	<div class="letra-circulo">
		<%= @user.name[0].capitalize %>
	</div>
	<h2 style="color:rgb(240,50,50);float: left">Calendario de<br><%= @user.name %></h2>
</div>


<div class="row">
	<div class="foto-user col-5 col-md-3">
		<img src="<%= @user.photo.normal %>" class="foto_usuario"> 
	</div>
</div>
<br>
<div id="calendar">
</div>

<script>
	$("#calendar").fullCalendar({
		events: '<%= user_calendar_path %>',
		
		eventDrop: function( event, delta, revertFunc, jsEvent, ui, view) {
			$.ajax({
				url: '/edit_calendar/' + event.id,
				type: 'PATCH',
				dataType: 'json',
				data: {
					user_activity: {start: event.start.format(), },
					authenticity_token: "<%= form_authenticity_token %>"
				}
			})
		},

		editable: true,
		displayEventTime: false,
	})
</script>