config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :collections, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :user_collections, only: [:create, :destroy]
  resources :user, only: [:show]
  resources :activities, only: [:create, :new, :show, :edit, :update, :destroy]
  resources :user_activities, only: [:create, :edit, :update, :destroy]
  resources :contacts, only: [:create, :destroy]
  resources :promote_activities, only: [:new, :create, :index, :destroy]
  resources :activity_collections, only: [:create, :destroy]

  get 'pages/index'
  get 'pages/configuration'
  get 'pages/politica'

  get 'user_calendar/:id', to: 'user#user_calendar', as: 'user_calendar'
  patch 'edit_calendar/:activity_id', to: 'user#update_calendar', as: 'update_user_calendar'
  
 

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        :omniauth_callbacks => "user/omniauth_callbacks",
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :user_activity, dependent: :destroy
	has_many :users, through: :user_activity, dependent: :destroy

	belongs_to :category, optional: true
	has_many :promote_activity, dependent: :destroy

	belongs_to :user, class_name: 'User', foreign_key: :owner_id

	mount_uploader :photo, ImageUploader

	has_many :activity_collection, dependent: :destroy
	has_many :collections, through: :activity_collection, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	

	def show
		@activity = Activity.find(params[:id])
		authorize! :show, @activity
		if user_signed_in?

			@contacts = User.find(current_user.id).contacting
	      	@contacts_activity = []
	      	@activity.users.each do |user|
	        	@contacts.each do |contact|
	          		if user.id == contact.followed_id
	            		@contacts_activity << User.find(contact.followed_id)
	          		end
	        	end
	      	end

			@user_act = UserActivity.where(user_id: current_user.id,activity_id: @activity.id)
			if @user_act != []
				if @user_act.first.status == 'realizada'				
					@registrada = true
					@user_activity = @user_act.first
				else
					@registrada = false
					@user_activity = @user_act.first
				end
			else
				@registrada = nil
			end
		end
	end

	def new
		@activity = Activity.new
		authorize! :new, @activity
		@categories = Category.all

	end

	def create
		@activity = Activity.new
		@activity.name = params[:activity][:name]
		@activity.category_id = params[:activity][:category_id]
		@activity.photo = params[:activity][:photo]
		@activity.remote_photo_url = params[:activity][:remote_photo_url]
		@activity.owner_id = current_user.id
		@activity.latitude = params[:activity][:latitude]
		@activity.longitude = params[:activity][:longitude]
		authorize! :create, @activity
		@activity.save
		redirect_to root_path, notice: 'la actividad fue creada. Puede ingresarla a su registro si lo desea'
	end

	def edit
		@activity = Activity.find(params[:id])
		authorize! :edit, @activity
		@categories = Category.all
		
	end

	def update
		@activity = Activity.find(params[:id])
		authorize! :update, @activity
		@activity.update(name: params[:activity][:name])
		@activity.update(author: params[:activity][:author])
		@activity.update(category_id: params[:activity][:category_id])
		@activity.update(photo: params[:activity][:photo])
		@activity.update(remote_photo_url: params[:activity][:remote_photo_url])
		@activity.update(latitude: params[:activity][:latitude])
		@activity.update(longitude: params[:activity][:longitude])
    	redirect_to user_path(current_user)
	end

	def destroy
		@activity = Activity.find(params[:id])
		authorize! :destroy, @activity
		@activity.destroy
		redirect_to pages_configuration_path, notice: 'la actividad fue borrada'
	end
	
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<h2>Editar Actividad </h2>
<br>
<% if user_signed_in? %>
	<%= form_with model: @activity, url: activity_path(@activity), method: :patch, local: true do |f| %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>	<br>

		<%= f.label :author %>
		<%= f.text_field :author %>	<br>

		<%= f.label :category %>
		<%= f.collection_select :category_id, @categories, :id, :name, :prompt => true %> <br>


	    <%= f.label :photo %> <br>
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><br>

		<br>
	    <i>Si la actividad es Trekking, agregar la ubicación:<br>
	    (utilizando punto como separador decimal)</i><br>
	    <%= f.label :latitude %>
		<%= f.text_field :latitude %>	<br>

		<%= f.label :longitude %>
		<%= f.text_field :longitude %>	<br>

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>

app/views/activities/new.html.erb
<h2>Crear nueva actividad </h2>
<br>

<% if user_signed_in? %>
	<%= form_with model: @activity, url: activities_path, method: :post, local: true do |f| %>
		
		<%= f.label :nombre %>: 
		<%= f.text_field :name %>	<br>

		<%= f.label :categoría %>: 
		<%= f.collection_select :category_id, @categories, :id, :name, :prompt => true %><br>

	    <%= f.label :photo %>: 
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><i>(puede subir una imagen o copiar el enlace de una imagen extraída de internet)</i><br>

	    <br>
	    <i>Si la actividad es Trekking, agregar la ubicación:<br>
	    (utilizando punto como separador decimal)</i><br>
	    <%= f.label :latitude %>: 
		<%= f.text_field :latitude %>	<br>

		<%= f.label :longitude %>: 
		<%= f.text_field :longitude %>	<br>

		<%= f.submit "Crear Actividad", :class => 'btn boton-config-titulo' %>

	<% end %>
<% end %>

app/views/activities/show.html.erb
<div id="fondo-act" class="fondo_activity">

	<div class="cuadro_centro_act">
		<div class="row">
			<div class="col-12 col-md-6">
				<h3><%= @activity.name %></h3>
				<p>Categoría: <%= @activity.category.name %></p>
				<img src="<%= @activity.photo.normal %>">
				<br><br><br><br>
				<h5>Contactos que registraron esta Actividad:</h5>
				<% if user_signed_in? %>
					<% @contacts_activity.each do |contact| %>
						<ul class="color-rojo-col">
							<li><%= link_to contact.name, user_path(contact) %></li>
						</ul>
					<% end %>
				<% end %>
			</div>
			<div class="col-12 col-md-6 boton">
				<% if user_signed_in? %>
					<% if @registrada == true %>
						<h6><i>Actividad registrada como Realizada</h6>
						<p>Fecha de realización: <%= @user_activity.start.strftime("%e de %b de %Y") %></i></p>
						<br><br>
						<%= link_to 'Marcar como actividad Pendiente por Realizar', user_activity_path(@user_activity,:enmendar => true,:status => 'por_hacer'), method: :patch, :class => 'btn btn-sm boton-tipo' %><br><br>
						<%= link_to 'Borrar del registro de actividades', user_activity_path(@user_activity.id), method: :delete, :class => 'btn btn-sm boton-tipo' %>

					<% elsif @registrada == false %>
						<h6><i>Actividad registrada como Pendiente por Realizar</i></h6>
						<p><i>Fecha de pronosticada: <%= @user_activity.start.strftime("%e de %b de %Y") %></i></p>
						<% if @user_activity.start < Time.now %>
							<strong>La actividad se encuentra atrasada por <%= distance_of_time_in_words(Time.now,@user_activity.start) %></strong><br>
						<% end %>
						<br><br>
						<%= link_to 'Registrar como Actividad Realizada', user_activity_path(@user_activity,:enmendar => false, :status => 'realizada'), method: :patch, :class => 'btn btn-sm boton-tipo' %><br><br>
						<%= link_to 'Borrar del registro de actividades', user_activity_path(@user_activity.id), method: :delete, :class => 'btn btn-sm boton-tipo' %>

					<% elsif @registrada == nil %>
						<h6><i>Actividad no Registrada</i></h6><br><br>
						<%= link_to 'Registrarla como Actividad Realizada', user_activities_path(:activity_id=> @activity.id, :status=> 'realizada',:user_id => current_user.id), method: :post, :class => 'btn btn-sm boton-tipo' %><br><br>
						<%= link_to 'Registrarla como actividad Pendiente por Realizar', user_activities_path(:activity_id=> @activity.id, :status=> 'por_hacer',:user_id => current_user.id), method: :post, :class => 'btn btn-sm boton-tipo' %>
					<% end %>
				<% end %>
				<br><br><br><br>
				<h5>Colecciones a la que pertence la actividad:</h5>
				<ul>
					<% @activity.collections.each do |collection| %>
						<li><h6><%= link_to collection.name, collection_path(collection) %></h6></li>
					<% end %>
				</ul>
			</div>
			<br>

		</div>
		<br>
		<% if can?(:edit, @activity) %>
			<%= link_to 'Editar actividad', edit_activity_path(@activity.id), :class => 'btn boton-tipo' %>
		<% end %>

		<img src="<%= @activity.photo %>" id="lo" style="display: none">
	</div>
</div>

<script>
		
		$("#fondo-act").backstretch(document.getElementById("lo").src)
		
		

</script>