config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :collections, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :user_collections, only: [:create, :destroy]
  resources :user, only: [:show]
  resources :activities, only: [:create, :new, :show, :edit, :update, :destroy]
  resources :user_activities, only: [:create, :edit, :update, :destroy]
  resources :contacts, only: [:create, :destroy]
  resources :promote_activities, only: [:new, :create, :index, :destroy]
  resources :activity_collections, only: [:create, :destroy]

  get 'pages/index'
  get 'pages/configuration'
  get 'pages/politica'

  get 'user_calendar/:id', to: 'user#user_calendar', as: 'user_calendar'
  patch 'edit_calendar/:activity_id', to: 'user#update_calendar', as: 'update_user_calendar'
  
 

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        :omniauth_callbacks => "user/omniauth_callbacks",
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
    if user.nil?
        can [:index, :politica, :show], :all
        can :read, ActiveAdmin::Page, name: 'Dashboard'
    elsif user.role == 'admin'
        can [:manage], :all
    elsif user.player?
        can [:index, :show, :configuration], :all


        can [:destroy], PromoteActivity, user_id: user.id
        can [:new, :create], PromoteActivity

        can [:manage], [Billing], user_id: user.id

        can [:create, :new], Activity
        can [:create, :new, :update, :edit, :destroy], Activity, owner_id: user.id

        can [:manage], [UserActivity], user_id: user.id

        can [:create, :new], Collection
        can [:edit, :update, :destroy], [Collection], owner_id: user.id

        can [:create, :destroy], [ActivityCollection], {collection: {owner_id: user.id}}

        can [:create, :destroy], UserCollection, user_id: user.id

        can [:create, :destroy], Contact, user_id: user.id

        can [:user_calendar], :all
        can [:update_calendar], :all, user_id: user.id
        
        can :read, ActiveAdmin::Page, name: 'Dashboard'
        
    end
        
        



    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :user_activity, dependent: :destroy
	has_many :users, through: :user_activity, dependent: :destroy

	belongs_to :category, optional: true
	has_many :promote_activity, dependent: :destroy

	belongs_to :user, class_name: 'User', foreign_key: :owner_id

	mount_uploader :photo, ImageUploader

	has_many :activity_collection, dependent: :destroy
	has_many :collections, through: :activity_collection, dependent: :destroy
end

app/models/actuser_photo.rb
class ActuserPhoto < ApplicationRecord
  belongs_to :user_activity
  mount_uploader :photo, ActsusUploader
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :player]
  attribute :role, :integer, default: :player
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :promote_activity
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :activities, dependent: :destroy
end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :activity_collection, dependent: :destroy
	has_many :activities, through: :activity_collection, dependent: :destroy
	mount_uploader :photo, ImageUploader

	has_many :user_collection, dependent: :destroy
	has_many :users, through: :user_collection, dependent: :destroy

	belongs_to :user, class_name: 'User', foreign_key: :owner_id
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user, class_name: 'User', foreign_key: 'user_id'
	belongs_to :followed, class_name: 'User', foreign_key: 'user_id'

	attribute :blocked, :boolean, default: false

	validate :user_different_from_followed

	def user_different_from_followed
		if self.user_id == self.followed_id
			errors.add(:base, 'a must be different to b')
		end
	end
end

app/models/promote_activity.rb
class PromoteActivity < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  belongs_to :billing, optional: true

  attribute :payed, :boolean, default: false

  validates :amount, :activity_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  enum role: [:admin, :player]
  attribute :role, :integer, default: :player

  has_many :user_activity
  has_many :activities, through: :user_activity
  has_many :promote_activity
  has_many :billings

  has_many :ownactivity, class_name: 'Activity', foreign_key: :owner_id

  has_many :owncollection, class_name: 'Collection', foreign_key: :owner_id

  has_many :contacting, class_name: 'Contact', foreign_key: :user_id
  has_many :contacted, class_name: 'Contact', foreign_key: :followed_id

  mount_uploader :photo, ImageUploader

  has_many :user_collection
  has_many :collections, through: :user_collection

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  attribute :start, :datetime, default: Time.now
  validates :start, presence: true
  
  validates :user_id, uniqueness: { scope: :activity_id,
    message: "Error" }

   has_many :actuser_photo, dependent: :destroy

   enum status: [:por_hacer, :realizada, :pendiente]

   scope :por_realizar, ->{ where(status: 'por_hacer')}
   scope :realizadas, ->{ where(status: 'realizada')}
   scope :pendientes, ->{ where(status: 'pendiente')}
end

app/models/user_collection.rb
class UserCollection < ApplicationRecord
  belongs_to :user
  belongs_to :collection

  validates :user_id, uniqueness: { scope: :collection_id,
    message: "Error" }

  enum status: [:siguiendo, :completa]
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<% if params[:q].present? %>
  <% @entities = Activity.where('name like ?', "%#{params[:q]}%") + Collection.where('name like ?', "%#{params[:q]}%") %>
<% else %>
  <% @entities = [] %>
<% end %>



<div class="nav-top row">

    <div class="col-3 buscador">

      <form>
        <input name="q" placeholder="Buscar..." id="buscar">
      </form>

      <div id="resultado">
        <%= render 'pages/activity' %>
      </div>
      
    </div>
  
    <% if user_signed_in? %>

        <div class="offset-0 col-12 offset-md-3 col-md-6">

          <strong><%= link_to 'Mis Colecciones', user_path(current_user), :class => 'nav-elemento texto-barra' %></strong>

          <strong><%= link_to 'Mi configuración', pages_configuration_path, :class => 'nav-elemento texto-barra' %></strong>
        </div>

        <div class="offset-4 offset-md-0 col-md-3 salir">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete, :class => 'nav-elemento texto-barra' %>

       </div>
    <% else %>

      <div class="col-12 offset-0 col-md-6 offset-md-6 nav-topleft">

        <%= link_to 'Ingresar', new_user_session_path, :class => 'nav-elemento texto-barra' %>

        <%= link_to 'Registrarse', new_user_registration_path, :class => 'nav-elemento texto-barra' %>
      
      </div>
    <% end %>

  
</div>



<script>
  $("[name=q]").keyup(function(event){
    if($(this).val().length > 2 || $(this).val().length == 0){
      $.ajax({
        url: '<%= pages_index_path %>',
        type: 'GET',
        dataType: 'script',
        data: {q: $(this).val()
      }

    })}
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> - Collections - </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="//maps.google.com/maps/api/js?key=AIzaSyCK1GQ9GHyuGimFduBsfDzDokcTKQH2Z9k&libraries=visualization"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="logo">
    <a href="<%= root_path %>"><img src="<%= asset_path 'logo.png' %>" width="20%" ></a>
    </div>
    <div class="cuerpo">
    
      <%= render 'layouts/nav' %>

      <% if alert.present? %>
        <div class="alert alert-warning"> <%= alert %></div>
      <% end %>

      <% if notice.present? %>
        <div class="alert alert-success"> <%= notice %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/index.js.erb
$("#resultado").html("<%= j render 'activity' %>")

app/views/pages/_activity.html.erb
  <% @entities.each do |entity| %>
  <ul class="resultado_fila">
  	<%if entity.class == Activity %>
  		<li><%= link_to entity.name, activity_path(entity.id) %> | <%= entity.category.name %></li>
  	<% else %>
  		<li><%= link_to entity.name, collection_path(entity.id) %> | Collection </li>
  	<% end %>
  </ul>
  <% end %>

     

app/views/pages/configuration.html.erb
<br>
<div class="titulo-config">
	<h5>Configuración de <%= @user.name %></h5>
	<br>
	<%= link_to 'Ir a datos de la cuenta', edit_user_registration_path, :class => 'btn boton-config-titulo' %><br><br>
	<%= link_to 'Promocionar mis Actividades/Colecciones', new_promote_activity_path, :class => 'btn boton-config-titulo' %>
	<%= link_to 'Ver mis Promociones', promote_activities_path, :class => 'btn boton-config-titulo' %>
</div>
<br><br>

	
<div class="row">
	<div class="col-12 col-md-6">
		<h6>Actividades creadas por <%= @user.name %>:</h6>
		<table class="table">
			<%if @user.ownactivity == [] %>
				<br><p><%= @user.name %> no ha creado actividades</p>
			<% else %>
				<% @user.ownactivity.each do |act| %>
					<tr>
						<td class="elemento-config"><%= link_to act.name, activity_path(act) %></td>
						<td><%= link_to 'editar', edit_activity_path(act), :class => 'btn boton-config' %></td>
						<td><%= link_to 'borrar', activity_path(act), method: :delete, :class => 'btn boton-config' %></td>
						<td></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>

	<div class="col-12 col-md-6">
		<table class="table">
			<%if @user.owncollection == [] %>
				<br><p><%= @user.name %> no ha creado colecciones</p>
			<% else %>
				<h6>Colecciones creadas por <%= @user.name %>:</h6>
				

				<% @user.owncollection.each do |col| %>
					<tr>
						<td class="elemento-config"><%= link_to col.name, collection_path(col) %></td>
						<td><%= link_to 'editar', edit_collection_path(col), :class => 'btn boton-config' %></td>
						<td><%= link_to 'borrar', collection_path(col), method: :delete, :class => 'btn boton-config' %></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	</div>
</div>

app/views/pages/index.html.erb
<% if user_signed_in? %>
	<div class="crear">
		<%= link_to 'Crear nueva Actividad', new_activity_path %> | 
		<%= link_to 'Crear nueva Colección', new_collection_path %><br>
	</div>
<% end %>

<br><br>


<div class="row">
	<div class="col-md-3 col-12">
		
		<h5>Colecciones</h5>
		<% @collections.each do |collection| %>
			<div class="collection_index p-1">
				<%= link_to collection.name, collection_path(collection) %><br>
				<img src="<%= collection.photo.normal %>" >
				
			</div>
		<% end %><br><br>
		
		<h5>Mis Contactos</h5>
		<% if user_signed_in? %>
			<% @contacts.each do |contact| %>
				<div class="collection_index">
					<img src="<%= User.find(contact.followed_id).photo.thumb %>" >
					<%= link_to User.find(contact.followed_id).name, user_path(User.find(contact.followed_id)) %><br>
				</div>
			<% end %>
		<% end %>
		<br>
		<h5>Otros Usuarios registrados</h5>
		<% @users.sample(8).each do |user| %>
			<div class="collection_index">
				<img src="<%= user.photo.thumb %>" >
				<%= link_to user.name, user_path(user) %> <br>
			</div>
		<% end %>

	</div>
	<div class="col-md-6 col-12 mt-1"><br>
		
		<% if not user_signed_in? %>
			<div class="text-center">
				<br><i>¡El registro de actividades se encuentra vacío!<br>
			Comienza registrándote o ingresando como usuario. Luego marca las actividades que hayas realizado y sigue a otros usuarios.</i>
			</div>
		<% elsif @sucesos == [] %>
			<div class="text-center">
				<br><i>¡El registro de actividades se encuentra vacío!<br>
			Comienza marcando las actividades que hayas realizado y a siguiendo a otros usuarios.</i>
			</div>
		<% else %>
			<% @sucesos.each do |evento|%>
				<div class="evento row">
					
					<div class="">
						<img src="<%= evento.user.photo.thumb %>" class="foto-index">
					</div>
					<div class="col-9">
						<p class="texto-index"><strong><%= link_to evento.user.name, user_path(evento.user_id) %></strong>
							<% if evento.status == "realizada" %>
								<%= evento.activity.category.past %>
							<% else %>
								<%= evento.activity.category.futuro %>
							<% end %>
							
						<%= link_to evento.activity.name, activity_path(evento.activity.id) %><br>
						Categoría: <%= evento.activity.category.sustantivo %></p>
					</div>
					<div>
						<img src="<%= evento.activity.photo.normal %>">
						<% evento.actuser_photo.each do |pho| %>
							<img src="<%= pho.photo %>">
						<% end %>
						<br>
						<p><%= time_ago_in_words(evento.created_at) %></p>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
	<div class="col-md-3">
		<h5>Otras Actividades</h5>

		<% @promotes.shuffle.each do |promote| %>
			<div class="collection_index p-2">
				<%= link_to promote.name, activity_path(promote) %><br>
				Categoría: <%= promote.category.sustantivo %><br>
				<img src="<%= promote.photo.normal %>"><br>
			</div>
		<% end %>

	</div>
<div>


<br>